name: Obtener Tag de la Rama Mergeada

on:
  push:
    branches:
      - main

jobs:
  obtener-tag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Obtener Información del Evento
      run: |
        TAG_NAME=$(git describe --tags --abbrev=0 ${{ github.event.before }})
        echo "El último tag en la rama mergeada fue: $TAG_NAME"