name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Tag Information
      run: |
        echo "Ref: $GITHUB_REF"
        echo "SHA: $GITHUB_SHA"
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "This push is associated with a tag."
          tag_name=$(echo $GITHUB_REF | sed 's/^refs\/tags\///')
          echo "Tag Name: $tag_name"
        else
          echo "This push is not associated with a tag."
        fi