name: Obtener Tag de la Rama Mergeada

on:
  push:
    branches:
      - main

jobs:
  obtener-tag:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo ${{ github.ref }}